#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume # Or your preferred title for the browser tab
url: 'https://NayeemAhsan.github.io' # CRITICAL: Your root user page URL

#change it according to your repository name
# disabling since we are using a custom domain
baseurl: '' # CRITICAL: Should be empty for a user page like NayeemAhsan.github.io

description: A beautiful Jekyll theme for creating resume # Or your site description
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1 # This is the theme developer's Google Analytics. You'll want to remove or replace it with your own.

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false