# Site Settings
title: My Resume # Or "Nayeem Ahsan - AI/ML Portfolio" etc.
url: 'https://NayeemAhsan.github.io' # Correct root URL
baseurl: '' # EMPTY for a user page repository named <username>.github.io

description: A beautiful Jekyll theme for creating resume # Your description
theme_skin: blue 
chrome_mobile_color: 

# Tracker
# analytics: UA-83979019-1 # REMOVE or REPLACE with your own Google Analytics ID

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html: 
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false